### ISSUE TITLE
" too short, trying to add redis cluster instance to RedisInsights

### ISSUE THREAD

**Issue by bschaatsbergen** [RedisLabs/redislabs-docs#1372]
**Current behavior** (A short description of what you found)
When setting up a redis docker cluster  I receive the following error, does anyone have an idea?
![image](https://user-images.githubusercontent.com/58337159/117883019-c1eb6980-b25f-11eb-99b5-7069dd766088.png)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)
my docker compose is as following:

```
version: "3.9"
services:
    redis-master-1:  
        image: redis
        command: 
            ["redis-server", "/etc/redis/redis.conf"]
        volumes:
        - ./redis.conf:/etc/redis/redis.conf
        ports:
        - "6379:6379"
    redis-slave-1:  
        image: redis
        command: 
            ["redis-server", "/etc/redis/redis.conf"]
        volumes:
        - ./redis.conf:/etc/redis/redis.conf
        ports:
        - "6380:6379"
```
