### ISSUE TITLE
add passing environment variable for target redis hosts in redisinsight k8s deployment yaml

### ISSUE THREAD

**Issue by oguzhanaygn** [RedisLabs/redislabs-docs#1532]
Hi, recently i'm working on deploying redisinsight to my AWS EKS cluster, I don't want to manage/add any of my infra component manually, so I'm trying to pass my redis hosts as environment variables to k8s deployment yaml. But as far as I understood, it is not being supported.

It can be very useful to be able to pass host & port variables for target redis databases that we want to connect via redisinsights.

Something like REDIS_HOSTS ;
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace : xxx
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 10%
    type: RollingUpdate
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        owner: xxx
        app: redisinsight
    spec:
      containers:
      - name:  redisinsight
        image: redislabs/redisinsight:1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: db
          mountPath: /db
        ports:
        - containerPort: 8001
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: RIHOST
          value: xxx.yyy.zzz
        - name: REDIS_HOSTS
          value: redishost1.example.com:6379,redishost2.example.com:6379
      volumes:
      - name: db
        emptyDir: {}
```
The example above enables us to configure our redis hosts at the deployment phase, so after deployment, our environment doesn't need extra host adding process, we will be ready to go at the beginning.

Any help appreciated.
Thank you.
Regards.
